[package]
name = "rcol"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4"
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
unicode-width = "0.2"

[[bin]]
name = "rcol"
path = "src/main.rs"

[lib]
name = "rcol"
path = "src/lib.rs"
